# Generated by Django 3.2.7 on 2021-09-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_postcode', models.CharField(max_length=10)),
                ('end_postcode', models.CharField(max_length=10)),
            ],
        ),
    ]
