# Generated by Django 3.2.7 on 2021-09-12 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postcodes', '0004_alter_postcode_end_postcode'),
    ]

    operations = [
    ]
