# Generated by Django 3.2.7 on 2021-09-12 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postcodes', '0006_postcode_measurement_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcode',
            name='measurement_choice',
        ),
    ]
