# Generated by Django 3.2.7 on 2021-09-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcodes', '0007_remove_postcode_measurement_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcode',
            name='measurement_choice',
            field=models.CharField(choices=[('KM', 'km'), ('M', 'miles')], default='KM', max_length=22),
            preserve_default=False,
        ),
    ]
